# This is a basic workflow to help you get started with Actions

name: Add To Projects

# Controls when the workflow will run
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.4.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/users/jmassardo/projects/4
          # A GitHub personal access token with write access to the project
          github-token: ${{ secrets.PROJECTS_SECRET }}
