name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues with `hack` label to project `
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'hack Time')
      with:
        project: 'https://github.com/jmassardo/action_test/projects/1'
        column_name: 'To do'
