# This is a basic workflow to help you get started with Actions

name: Add To Projects

# Controls when the workflow will run
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Add To GitHub projects
        run: |
          gh api graphql -f query='
            mutation ($project_node_id: ID!, $issue_url: String!){
              addProjectV2DraftIssue(input: {projectId: $project_node_id title: $issue_url}) {
                projectItem {
                  id
                }
              }
            }' -f project_node_id=$PROJECT_NODE_ID -f issue_url=$ISSUE_URL
        env:
          PROJECT_NODE_ID: ${secrets.PROJECT_NODE_ID}
          PROJECTS_SECRET: ${secrets.PROJECTS_SECRET}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          
