name: issue_comments

on: issue_comment

jobs:
  process-issue:
    if: contains(github.event.issue.labels.*.name, 'new-topic') && ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo $USER commented on issue $NUMBER. Comment body: $BODY
        env:
          USER: ${{ github.event.issue.user.login }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: ${{ github.event.issue }}
