name: call_api

on:
  workflow_dispatch:

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
          --header 'authorization: Bearer ${{ secrets.GH_PAT }}' \
          --header 'content-type: application/json' 
