name: Create Compliance Issues
on:
  pull_request:
    types: [opened]
jobs:
  create-issues:
    name: Create Compliance Issues and Update PR Body
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python3
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'
      - name: run script
        run: |
          pip3 install requests
          python3 ./scripts/compliance.py
        env:
          PULL_PAYLOAD: ${{ toJSON(github.event.pull_request) }}