name: date_test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo only
        run: echo "TODAY=$(date -v+72H +'%m-%d-%Y')"
      - name: Echo to env
        run: echo "TODAY=$(date -v+72H +'%m-%d-%Y')" >> $GITHUB_ENV
      - name: Echo from env
        run: echo env.TODAY
