name: dynamic_matrix

on:
  workflow_dispatch:

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: generate matrix
        id: generate-matrix
        run: |
          export MATRIX_JSON='{"projects": ["project1","project2","project3"]}'
          echo "::set-output name=matrix::${MATRIX_JSON}"
  build:
    runs-on: ubuntu-latest
    needs: metadata
    strategy:
      matrix: ${{ fromJson(needs.metadata.outputs.matrix) }}
    steps:
      - name: Run a one-line script
        run: echo "Hello, world ${{ matrix.projects }} !"
