name: say-hi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lowply/issue-from-template@v1
      env:
        IFT_TEMPLATE_NAME: .github/ISSUE_TEMPLATE/action_issue.md
        ADD_DATES: 7
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
