name: say-hi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  issues:
    types: [opened]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jmassardo/hello-world-javascript-action@v1.1
      with:
        who-to-greet: 'Mona the Octocat'
