name: say-hi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lowply/issue-from-template@v0.1.3
      env:
        IFT_TEMPLATE_NAME: action_issue.md
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
