name: 'Label Issue'

on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  label_issue:
    if:  ${{ !contains(github.event.issue.labels.*.name, 'totango') }}
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@master
        with:
          add-labels: "totango"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
