name: 'Label Actions'

on:
  issues:
    types: [created, labeled, unlabeled]

jobs:
  label_issue:
    if:  "!contains(github.event.issue.labels.*.name, 'totango')"
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@master
        with:
          add-labels: "Slack"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
