name: reusable
on:
  workflow_call:
    inputs:
      REGISTRY_URL:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
jobs:
  Login-to-ACR:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY_URL}}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Run a one-line script
        run: docker run ${{ inputs.REGISTRY_URL}}/safe-settings:latest
  Call-Container-Directly:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.REGISTRY_URL}}/safe-settings:latest
      credentials:
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    steps:
      - name: Run command on container
        run: whoami