name: local_call

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable.yml
    with:
      REGISTRY_URL: jmassardodocker.azurecr.io
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET:  ${{ secrets.AZURE_CLIENT_SECRET }}