name: totango

on:
  issues:
    types: [opened, closed]
  issue_comment:

jobs:
  process-issue:
    # Only run if the issue has the correct label or is an issue comment
    if: contains(github.event.issue.labels.*.name, 'totango-sync')  && ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: jmassardo/issues-to-totango@v1.1
      with:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ACTIVITY_TYPE: "adoption"
        TOUCHPOINT_REASON: "e53621bc-f66a-49f0-a886-537b5c64df22"
