name: totango

on:
  issues:
    types: [opened, closed]
  issue_comment:

jobs:
  process-issue:
    # Only run if the issue has the correct label or is an issue comment
    if: contains(github.event.issue.labels.*.name, 'totango-sync')
    runs-on: ubuntu-latest
    steps:
    - uses: jmassardo/issues-to-totango@main
      with:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ACTIVITY_TYPE: "nurture" #${{ secrets.ACTIVITY_TYPE }}
        TOUCHPOINT_TYPE: ${{ secrets.TOUCHPOINT_TYPE }}
        TOUCHPOINT_TAGS: ${{ secrets.TOUCHPOINT_TAGS }}
