name: totango

on:
  issues:
    types: [closed, labeled, edited]
  issue_comment:

jobs:
  process-issue:
    # Prevent action from trying to parse issues that don't have a label which this action supports
    if: contains(github.event.issue.labels.*.name, 'task') ||
        contains(github.event.issue.labels.*.name, 'touchpoint')

    runs-on: ubuntu-latest
    steps:
    - uses: jmassardo/issues-to-totango@v2.0.0 #@version2.0
      with:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ACTIVITY_TYPE: "nurture_1618339431022" #${{ secrets.ACTIVITY_TYPE }}
        TOUCHPOINT_TYPE: ${{ secrets.TOUCHPOINT_TYPE }}
        TOUCHPOINT_TAGS: ${{ secrets.TOUCHPOINT_TAGS }}
        TASK_ASSIGNEE: ${{ vars.TASK_ASSIGNEE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
