name: totango

on:
  issues:
    types: [opened, closed]
  issue_comment:

jobs:
  process-issue:
    # Only run if the issue has the correct label or is an issue comment
    if: contains(github.event.issue.labels.*.name, 'totango-sync')  && ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: jmassardo/issues-to-totango@jrm/fix-touchpoint-reasons
      with:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ACTIVITY_TYPE: "adoption"
        TOUCHPOINT_TYPE: "7112c2e3-294a-490a-8307-eba7f30c1cd7"
        TOUCHPOINT_REASON: "8c91d24d-09aa-4d3e-a3c4-b3782803c33b"
